# Data Extraction

This notebook extracts structured tabular data from the raw JSON files collected in `01_collection.ipynb`. Each raw file contains a GeoJSON response from the IEM Convective Outlook Warning (COW) API for a single NWS Weather Forecast Office and calendar year. The extraction process flattens those responses into two analysis-ready tables: `events`, containing one row per warning event, and `stormreports`, containing one row per Local Storm Report (LSR). Both tables are written as CSV files to `data/extracted/`, which serves as an immutable checkpoint of the source data before any cleaning or transformation is applied. No analytical decisions are made here; the output reflects the content of the source data as faithfully as possible.

## Implementation

Extraction is implemented by `COWExtractor` in `src/processing/extractor.py`. It reads every `{WFO}_{YEAR}.json` file from `data/raw/COW/`, flattens the GeoJSON feature properties into rows, and writes two CSV files to `data/extracted/` as an immutable checkpoint before any cleaning decisions are applied.

| Method | Output |
|---|---|
| `extract_events()` | One row per warning event; `wfo` and `year` derived from filename |
| `extract_stormreports()` | One row per LSR; `warned=False` rows are unwarned storm reports (misses) |

Geometry is excluded from both tables because the analysis is statistical, not spatial. API-supplied `wfo` and `year` fields are replaced by filename-derived values to ensure consistency across all files.

In [1]:
import logging
import sys
from pathlib import Path

sys.path.append("../src")

from processing import COWExtractor

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-7s  %(message)s",
    datefmt="%H:%M:%S",
)

# --- Configuration ---

# Input: raw JSON files written by 01_collection.ipynb
COW_DIR = Path("../data/raw/COW")

# Output: flattened CSV files, immutable checkpoint before cleaning.
# Cleaning decisions are applied in 03_cleaning.ipynb → data/processed/
EXTRACTED_DIR = Path("../data/extracted")

## Events

One row per warning event issued by a WFO. Key fields for analysis: `phenomena`, `fcster`, `issue`, `expire`, `verify`, `lead0`, and `significance`. The `stormreports` and `lead0` columns are null for unverified events (i.e., those with no matching LSR).

In [2]:
extractor = COWExtractor(raw_dir=COW_DIR, extracted_dir=EXTRACTED_DIR)
print(extractor)

COWExtractor(raw=../data/raw/COW, extracted=../data/extracted)

In [3]:
events = extractor.extract_events()
print(f"{len(events):,} rows × {len(events.columns)} columns")
events.head()

15:18:04  INFO     Extracting events from ABQ_2020.json ...
15:18:04  INFO     Extracting events from ABQ_2021.json ...
15:18:04  INFO     Extracting events from ABQ_2022.json ...
15:18:04  INFO     Extracting events from ABQ_2023.json ...
15:18:04  INFO     Extracting events from ABQ_2024.json ...
15:18:04  INFO     Extracting events from ABQ_2025.json ...
15:18:04  INFO     Extracting events from ABR_2020.json ...
15:18:04  INFO     Extracting events from ABR_2021.json ...
15:18:04  INFO     Extracting events from ABR_2022.json ...
15:18:04  INFO     Extracting events from ABR_2023.json ...
15:18:04  INFO     Extracting events from ABR_2024.json ...
15:18:04  INFO     Extracting events from ABR_2025.json ...
15:18:04  INFO     Extracting events from AFC_2020.json ...
15:18:04  WARNING  AFC_2020.json: no events found, skipping
15:18:04  INFO     Extracting events from AFC_2021.json ...
15:18:04  WARNING  AFC_2021.json: no events found, skipping
15:18:04  INFO     Extracting events from AFC_2022.json ...
15:18:04  WARNING  AFC_2022.json: no events found, skipping
15:18:04  INFO     Extracting events from AFC_2023.json ...
15:18:04  WARNING  AFC_2023.json: no events found, skipping
15:18:04  INFO     Extracting events from AFC_2024.json ...
15:18:04  WARNING  AFC_2024.json: no events found, skipping
15:18:04  INFO     Extracting events from AFC_2025.json ...
15:18:04  WARNING  AFC_2025.json: no events found, skipping
15:18:04  INFO     Extracting events from AFG_2020.json ...
15:18:04  WARNING  AFG_2020.json: no events found, skipping
15:18:04  INFO     Extracting events from AFG_2021.json ...
15:18:04  WARNING  AFG_2021.json: no events found, skipping
15:18:04  INFO     Extracting events from AFG_2022.json ...
15:18:04  WARNING  AFG_2022.json: no events found, skipping
15:18:04  INFO     Extracting events from AFG_2023.json ...
15:18:04  WARNING  AFG_2023.json: no events found, skipping
15:18:04  INFO     Extracting events from AFG_2024.json ...
15:18:04  WARNING  AFG_2024.json: no events found, skipping
15:18:04  INFO     Extracting events from AFG_2025.json ...
15:18:04  WARNING  AFG_2025.json: no events found, skipping
15:18:04  INFO     Extracting events from AJK_2020.json ...
15:18:04  WARNING  AJK_2020.json: no events found, skipping
15:18:04  INFO     Extracting events from AJK_2021.json ...
15:18:04  WARNING  AJK_2021.json: no events found, skipping
15:18:04  INFO     Extracting events from AJK_2022.json ...
15:18:04  WARNING  AJK_2022.json: no events found, skipping
15:18:04  INFO     Extracting events from AJK_2023.json ...
15:18:04  WARNING  AJK_2023.json: no events found, skipping
15:18:04  INFO     Extracting events from AJK_2024.json ...
15:18:04  WARNING  AJK_2024.json: no events found, skipping
15:18:04  INFO     Extracting events from AJK_2025.json ...
15:18:04  WARNING  AJK_2025.json: no events found, skipping
15:18:04  INFO     Extracting events from AKQ_2020.json ...
15:18:04  INFO     Extracting events from AKQ_2021.json ...
15:18:04  INFO     Extracting events from AKQ_2022.json ...
15:18:04  INFO     Extracting events from AKQ_2023.json ...
15:18:04  INFO     Extracting events from AKQ_2024.json ...
15:18:04  INFO     Extracting events from AKQ_2025.json ...
15:18:04  INFO     Extracting events from ALY_2020.json ...
15:18:04  INFO     Extracting events from ALY_2021.json ...
15:18:04  INFO     Extracting events from ALY_2022.json ...
15:18:04  INFO     Extracting events from ALY_2023.json ...
15:18:04  INFO     Extracting events from ALY_2024.json ...
15:18:04  INFO     Extracting events from ALY_2025.json ...
15:18:04  INFO     Extracting events from AMA_2020.json ...
15:18:04  INFO     Extracting events from AMA_2021.json ...
15:18:04  INFO     Extracting events from AMA_2022.json ...
15:18:04  INFO     Extracting events from AMA_2023.json ...
15:18:04  INFO     Extracting events from AMA_2024.json ...
15:18:04  INFO     Extracting events from AMA_2025.json ...
15:18:04  INFO     Extracting events from APX_2020.json ...
15:18:04  INFO     Extracting events from APX_2021.json ...
15:18:04  WARNING  APX_2021.json: no events found, skipping
15:18:04  INFO     Extracting events from APX_2022.json ...
15:18:04  INFO     Extracting events from APX_2023.json ...
15:18:04  WARNING  APX_2023.json: no events found, skipping
15:18:04  INFO     Extracting events from APX_2024.json ...
15:18:04  INFO     Extracting events from APX_2025.json ...
15:18:04  INFO     Extracting events from ARX_2020.json ...
15:18:04  INFO     Extracting events from ARX_2021.json ...
15:18:04  INFO     Extracting events from ARX_2022.json ...
15:18:04  INFO     Extracting events from ARX_2023.json ...
15:18:04  INFO     Extracting events from ARX_2024.json ...
15:18:04  INFO     Extracting events from ARX_2025.json ...
15:18:04  INFO     Extracting events from BGM_2020.json ...
15:18:04  INFO     Extracting events from BGM_2021.json ...
15:18:04  INFO     Extracting events from BGM_2022.json ...
15:18:04  INFO     Extracting events from BGM_2023.json ...
15:18:04  INFO     Extracting events from BGM_2024.json ...
15:18:04  INFO     Extracting events from BGM_2025.json ...
15:18:04  INFO     Extracting events from BIS_2020.json ...
15:18:04  INFO     Extracting events from BIS_2021.json ...
15:18:04  INFO     Extracting events from BIS_2022.json ...
15:18:04  INFO     Extracting events from BIS_2023.json ...
15:18:04  INFO     Extracting events from BIS_2024.json ...
15:18:04  INFO     Extracting events from BIS_2025.json ...
15:18:04  INFO     Extracting events from BMX_2020.json ...
15:18:04  INFO     Extracting events from BMX_2021.json ...
15:18:04  INFO     Extracting events from BMX_2022.json ...
15:18:04  INFO     Extracting events from BMX_2023.json ...
15:18:04  INFO     Extracting events from BMX_2024.json ...
15:18:04  INFO     Extracting events from BMX_2025.json ...
15:18:04  INFO     Extracting events from BOI_2020.json ...
15:18:04  WARNING  BOI_2020.json: no events found, skipping
15:18:04  INFO     Extracting events from BOI_2021.json ...
15:18:04  WARNING  BOI_2021.json: no events found, skipping
15:18:04  INFO     Extracting events from BOI_2022.json ...
15:18:04  WARNING  BOI_2022.json: no events found, skipping
15:18:04  INFO     Extracting events from BOI_2023.json ...
15:18:04  WARNING  BOI_2023.json: no events found, skipping
15:18:04  INFO     Extracting events from BOI_2024.json ...
15:18:04  WARNING  BOI_2024.json: no events found, skipping
15:18:04  INFO     Extracting events from BOI_2025.json ...
15:18:04  WARNING  BOI_2025.json: no events found, skipping
15:18:04  INFO     Extracting events from BOU_2020.json ...
15:18:04  INFO     Extracting events from BOU_2021.json ...
15:18:04  INFO     Extracting events from BOU_2022.json ...
15:18:04  INFO     Extracting events from BOU_2023.json ...
15:18:04  INFO     Extracting events from BOU_2024.json ...
15:18:04  INFO     Extracting events from BOU_2025.json ...
15:18:04  INFO     Extracting events from BOX_2020.json ...
15:18:04  INFO     Extracting events from BOX_2021.json ...
15:18:04  INFO     Extracting events from BOX_2022.json ...
15:18:04  INFO     Extracting events from BOX_2023.json ...
15:18:04  INFO     Extracting events from BOX_2024.json ...
15:18:04  INFO     Extracting events from BOX_2025.json ...
15:18:04  INFO     Extracting events from BRO_2020.json ...
15:18:04  INFO     Extracting events from BRO_2021.json ...
15:18:04  INFO     Extracting events from BRO_2022.json ...
15:18:04  WARNING  BRO_2022.json: no events found, skipping
15:18:04  INFO     Extracting events from BRO_2023.json ...
15:18:04  INFO     Extracting events from BRO_2024.json ...
15:18:04  INFO     Extracting events from BRO_2025.json ...
15:18:04  INFO     Extracting events from BTV_2020.json ...
15:18:04  INFO     Extracting events from BTV_2021.json ...
15:18:04  WARNING  BTV_2021.json: no events found, skipping
15:18:04  INFO     Extracting events from BTV_2022.json ...
15:18:04  INFO     Extracting events from BTV_2023.json ...
15:18:04  INFO     Extracting events from BTV_2024.json ...
15:18:04  INFO     Extracting events from BTV_2025.json ...
15:18:04  INFO     Extracting events from BUF_2020.json ...
15:18:04  INFO     Extracting events from BUF_2021.json ...
15:18:04  INFO     Extracting events from BUF_2022.json ...
15:18:04  INFO     Extracting events from BUF_2023.json ...
15:18:04  INFO     Extracting events from BUF_2024.json ...
15:18:04  INFO     Extracting events from BUF_2025.json ...
15:18:04  INFO     Extracting events from BYZ_2020.json ...
15:18:04  WARNING  BYZ_2020.json: no events found, skipping
15:18:04  INFO     Extracting events from BYZ_2021.json ...
15:18:04  WARNING  BYZ_2021.json: no events found, skipping
15:18:04  INFO     Extracting events from BYZ_2022.json ...
15:18:04  INFO     Extracting events from BYZ_2023.json ...
15:18:04  WARNING  BYZ_2023.json: no events found, skipping
15:18:04  INFO     Extracting events from BYZ_2024.json ...
15:18:04  INFO     Extracting events from BYZ_2025.json ...
15:18:04  INFO     Extracting events from CAE_2020.json ...
15:18:04  INFO     Extracting events from CAE_2021.json ...
15:18:04  INFO     Extracting events from CAE_2022.json ...
15:18:04  INFO     Extracting events from CAE_2023.json ...
15:18:04  INFO     Extracting events from CAE_2024.json ...
15:18:04  INFO     Extracting events from CAE_2025.json ...
15:18:04  INFO     Extracting events from CAR_2020.json ...
15:18:04  INFO     Extracting events from CAR_2021.json ...
15:18:04  INFO     Extracting events from CAR_2022.json ...
15:18:04  INFO     Extracting events from CAR_2023.json ...
15:18:04  WARNING  CAR_2023.json: no events found, skipping
15:18:04  INFO     Extracting events from CAR_2024.json ...
15:18:04  INFO     Extracting events from CAR_2025.json ...
15:18:04  INFO     Extracting events from CHS_2020.json ...
15:18:04  INFO     Extracting events from CHS_2021.json ...
15:18:04  INFO     Extracting events from CHS_2022.json ...
15:18:04  INFO     Extracting events from CHS_2023.json ...
15:18:04  INFO     Extracting events from CHS_2024.json ...
15:18:04  INFO     Extracting events from CHS_2025.json ...
15:18:04  INFO     Extracting events from CLE_2020.json ...
15:18:04  INFO     Extracting events from CLE_2021.json ...
15:18:04  INFO     Extracting events from CLE_2022.json ...
15:18:04  INFO     Extracting events from CLE_2023.json ...
15:18:04  INFO     Extracting events from CLE_2024.json ...
15:18:04  INFO     Extracting events from CLE_2025.json ...
15:18:04  INFO     Extracting events from CRP_2020.json ...
15:18:04  INFO     Extracting events from CRP_2021.json ...
15:18:04  INFO     Extracting events from CRP_2022.json ...
15:18:04  INFO     Extracting events from CRP_2023.json ...
15:18:04  INFO     Extracting events from CRP_2024.json ...
15:18:04  INFO     Extracting events from CRP_2025.json ...
15:18:04  WARNING  CRP_2025.json: no events found, skipping
15:18:04  INFO     Extracting events from CTP_2020.json ...
15:18:04  INFO     Extracting events from CTP_2021.json ...
15:18:04  INFO     Extracting events from CTP_2022.json ...
15:18:04  INFO     Extracting events from CTP_2023.json ...
15:18:04  INFO     Extracting events from CTP_2024.json ...
15:18:04  INFO     Extracting events from CTP_2025.json ...
15:18:04  INFO     Extracting events from CYS_2020.json ...
15:18:04  INFO     Extracting events from CYS_2021.json ...
15:18:04  INFO     Extracting events from CYS_2022.json ...
15:18:04  INFO     Extracting events from CYS_2023.json ...
15:18:04  INFO     Extracting events from CYS_2024.json ...
15:18:04  INFO     Extracting events from CYS_2025.json ...
15:18:04  INFO     Extracting events from DDC_2020.json ...
15:18:04  INFO     Extracting events from DDC_2021.json ...
15:18:04  INFO     Extracting events from DDC_2022.json ...
15:18:04  INFO     Extracting events from DDC_2023.json ...
15:18:04  INFO     Extracting events from DDC_2024.json ...
15:18:04  INFO     Extracting events from DDC_2025.json ...
15:18:04  INFO     Extracting events from DLH_2020.json ...
15:18:04  INFO     Extracting events from DLH_2021.json ...
15:18:04  INFO     Extracting events from DLH_2022.json ...
15:18:04  INFO     Extracting events from DLH_2023.json ...
15:18:04  INFO     Extracting events from DLH_2024.json ...
15:18:04  INFO     Extracting events from DLH_2025.json ...
15:18:04  INFO     Extracting events from DMX_2020.json ...
15:18:04  INFO     Extracting events from DMX_2021.json ...
15:18:04  INFO     Extracting events from DMX_2022.json ...
15:18:04  INFO     Extracting events from DMX_2023.json ...
15:18:04  INFO     Extracting events from DMX_2024.json ...
15:18:04  INFO     Extracting events from DMX_2025.json ...
15:18:04  INFO     Extracting events from DTX_2020.json ...
15:18:04  WARNING  DTX_2020.json: no events found, skipping
15:18:04  INFO     Extracting events from DTX_2021.json ...
15:18:04  INFO     Extracting events from DTX_2022.json ...
15:18:04  INFO     Extracting events from DTX_2023.json ...
15:18:04  INFO     Extracting events from DTX_2024.json ...
15:18:04  INFO     Extracting events from DTX_2025.json ...
15:18:04  INFO     Extracting events from DVN_2020.json ...
15:18:04  INFO     Extracting events from DVN_2021.json ...
15:18:04  INFO     Extracting events from DVN_2022.json ...
15:18:04  INFO     Extracting events from DVN_2023.json ...
15:18:04  INFO     Extracting events from DVN_2024.json ...
15:18:04  INFO     Extracting events from DVN_2025.json ...
15:18:04  INFO     Extracting events from EAX_2020.json ...
15:18:04  INFO     Extracting events from EAX_2021.json ...
15:18:04  INFO     Extracting events from EAX_2022.json ...
15:18:04  INFO     Extracting events from EAX_2023.json ...
15:18:04  INFO     Extracting events from EAX_2024.json ...
15:18:04  INFO     Extracting events from EAX_2025.json ...
15:18:04  INFO     Extracting events from EKA_2020.json ...
15:18:04  WARNING  EKA_2020.json: no events found, skipping
15:18:04  INFO     Extracting events from EKA_2021.json ...
15:18:04  WARNING  EKA_2021.json: no events found, skipping
15:18:04  INFO     Extracting events from EKA_2022.json ...
15:18:04  WARNING  EKA_2022.json: no events found, skipping
15:18:04  INFO     Extracting events from EKA_2023.json ...
15:18:04  WARNING  EKA_2023.json: no events found, skipping
15:18:04  INFO     Extracting events from EKA_2024.json ...
15:18:04  WARNING  EKA_2024.json: no events found, skipping
15:18:04  INFO     Extracting events from EKA_2025.json ...
15:18:04  WARNING  EKA_2025.json: no events found, skipping
15:18:04  INFO     Extracting events from EPZ_2020.json ...
15:18:04  WARNING  EPZ_2020.json: no events found, skipping
15:18:04  INFO     Extracting events from EPZ_2021.json ...
15:18:04  WARNING  EPZ_2021.json: no events found, skipping
15:18:04  INFO     Extracting events from EPZ_2022.json ...
15:18:04  WARNING  EPZ_2022.json: no events found, skipping
15:18:04  INFO     Extracting events from EPZ_2023.json ...
15:18:04  WARNING  EPZ_2023.json: no events found, skipping
15:18:04  INFO     Extracting events from EPZ_2024.json ...
15:18:04  WARNING  EPZ_2024.json: no events found, skipping
15:18:04  INFO     Extracting events from EPZ_2025.json ...
15:18:04  WARNING  EPZ_2025.json: no events found, skipping
15:18:04  INFO     Extracting events from EWX_2020.json ...
15:18:04  INFO     Extracting events from EWX_2021.json ...
15:18:04  INFO     Extracting events from EWX_2022.json ...
15:18:04  INFO     Extracting events from EWX_2023.json ...
15:18:04  INFO     Extracting events from EWX_2024.json ...
15:18:04  INFO     Extracting events from EWX_2025.json ...
15:18:04  INFO     Extracting events from FFC_2020.json ...
15:18:04  INFO     Extracting events from FFC_2021.json ...
15:18:04  INFO     Extracting events from FFC_2022.json ...
15:18:04  INFO     Extracting events from FFC_2023.json ...
15:18:04  INFO     Extracting events from FFC_2024.json ...
15:18:04  INFO     Extracting events from FFC_2025.json ...
15:18:04  INFO     Extracting events from FGF_2020.json ...
15:18:04  INFO     Extracting events from FGF_2021.json ...
15:18:04  INFO     Extracting events from FGF_2022.json ...
15:18:04  INFO     Extracting events from FGF_2023.json ...
15:18:04  INFO     Extracting events from FGF_2024.json ...
15:18:04  INFO     Extracting events from FGF_2025.json ...
15:18:04  INFO     Extracting events from FGZ_2020.json ...
15:18:04  WARNING  FGZ_2020.json: no events found, skipping
15:18:04  INFO     Extracting events from FGZ_2021.json ...
15:18:04  INFO     Extracting events from FGZ_2022.json ...
15:18:04  WARNING  FGZ_2022.json: no events found, skipping
15:18:04  INFO     Extracting events from FGZ_2023.json ...
15:18:04  WARNING  FGZ_2023.json: no events found, skipping
15:18:04  INFO     Extracting events from FGZ_2024.json ...
15:18:04  INFO     Extracting events from FGZ_2025.json ...
15:18:04  INFO     Extracting events from FSD_2020.json ...
15:18:04  INFO     Extracting events from FSD_2021.json ...
15:18:04  INFO     Extracting events from FSD_2022.json ...
15:18:04  INFO     Extracting events from FSD_2023.json ...
15:18:04  INFO     Extracting events from FSD_2024.json ...
15:18:04  INFO     Extracting events from FSD_2025.json ...
15:18:04  INFO     Extracting events from FWD_2020.json ...
15:18:04  INFO     Extracting events from FWD_2021.json ...
15:18:04  INFO     Extracting events from FWD_2022.json ...
15:18:04  INFO     Extracting events from FWD_2023.json ...
15:18:04  INFO     Extracting events from FWD_2024.json ...
15:18:04  INFO     Extracting events from FWD_2025.json ...
15:18:04  INFO     Extracting events from GGW_2020.json ...
15:18:04  INFO     Extracting events from GGW_2021.json ...
15:18:04  INFO     Extracting events from GGW_2022.json ...
15:18:04  INFO     Extracting events from GGW_2023.json ...
15:18:04  INFO     Extracting events from GGW_2024.json ...
15:18:04  INFO     Extracting events from GGW_2025.json ...
15:18:04  WARNING  GGW_2025.json: no events found, skipping
15:18:04  INFO     Extracting events from GID_2020.json ...
15:18:04  INFO     Extracting events from GID_2021.json ...
15:18:04  INFO     Extracting events from GID_2022.json ...
15:18:04  INFO     Extracting events from GID_2023.json ...
15:18:04  INFO     Extracting events from GID_2024.json ...
15:18:04  INFO     Extracting events from GID_2025.json ...
15:18:04  INFO     Extracting events from GJT_2020.json ...
15:18:04  WARNING  GJT_2020.json: no events found, skipping
15:18:04  INFO     Extracting events from GJT_2021.json ...
15:18:04  WARNING  GJT_2021.json: no events found, skipping
15:18:04  INFO     Extracting events from GJT_2022.json ...
15:18:04  WARNING  GJT_2022.json: no events found, skipping
15:18:04  INFO     Extracting events from GJT_2023.json ...
15:18:04  WARNING  GJT_2023.json: no events found, skipping
15:18:04  INFO     Extracting events from GJT_2024.json ...
15:18:04  WARNING  GJT_2024.json: no events found, skipping
15:18:04  INFO     Extracting events from GJT_2025.json ...
15:18:04  INFO     Extracting events from GLD_2020.json ...
15:18:04  INFO     Extracting events from GLD_2021.json ...
15:18:04  INFO     Extracting events from GLD_2022.json ...
15:18:04  INFO     Extracting events from GLD_2023.json ...
15:18:04  INFO     Extracting events from GLD_2024.json ...
15:18:04  INFO     Extracting events from GLD_2025.json ...
15:18:04  INFO     Extracting events from GRB_2020.json ...
15:18:04  INFO     Extracting events from GRB_2021.json ...
15:18:04  INFO     Extracting events from GRB_2022.json ...
15:18:04  INFO     Extracting events from GRB_2023.json ...
15:18:04  WARNING  GRB_2023.json: no events found, skipping
15:18:04  INFO     Extracting events from GRB_2024.json ...
15:18:04  INFO     Extracting events from GRB_2025.json ...
15:18:04  INFO     Extracting events from GRR_2020.json ...

16,086 rows × 32 columns

,wfo,year,phenomena,eventid,sharedborder,issue,expire,statuses,fcster,svr_tornado_possible,...,stormreports,stormreports_all,verify,tor_in_svrtorpossible,lead0,areaverify,visual_imgurl,product_text,product_href,link
0,ABQ,2020,TO,1,40531.482739,2020-03-13T23:04:00Z,2020-03-13T23:30:00Z,EXP,DPorter,False,...,,,False,False,None,0.0,https://mesonet.agron.iastate.edu/GIS/radmap.p...,https://mesonet.agron.iastate.edu/api/1/nwstex...,https://mesonet.agron.iastate.edu/p.php?pid=20...,https://mesonet.agron.iastate.edu/vtec/f/2020-...
1,ABQ,2020,TO,2,0.000000,2020-03-13T23:20:00Z,2020-03-13T23:32:00Z,CAN,DPorter,False,...,,,False,False,None,0.0,https://mesonet.agron.iastate.edu/GIS/radmap.p...,https://mesonet.agron.iastate.edu/api/1/nwstex...,https://mesonet.agron.iastate.edu/p.php?pid=20...,https://mesonet.agron.iastate.edu/vtec/f/2020-...
2,ABQ,2021,TO,1,0.000000,2021-05-17T19:22:00Z,2021-05-17T19:45:00Z,EXP,44,False,...,,,False,False,NaN,0.0,https://mesonet.agron.iastate.edu/GIS/radmap.p...,https://mesonet.agron.iastate.edu/api/1/nwstex...,https://mesonet.agron.iastate.edu/p.php?pid=20...,https://mesonet.agron.iastate.edu/vtec/f/2021-...
3,ABQ,2021,TO,2,18209.013334,2021-05-17T22:42:00Z,2021-05-17T23:20:00Z,CAN,44,False,...,,,False,False,NaN,0.0,https://mesonet.agron.iastate.edu/GIS/radmap.p...,https://mesonet.agron.iastate.edu/api/1/nwstex...,https://mesonet.agron.iastate.edu/p.php?pid=20...,https://mesonet.agron.iastate.edu/vtec/f/2021-...
4,ABQ,2021,TO,3,47094.091641,2021-05-17T23:41:00Z,2021-05-17T23:55:00Z,CAN,44,False,...,,,False,False,NaN,0.0,https://mesonet.agron.iastate.edu/GIS/radmap.p...,https://mesonet.agron.iastate.edu/api/1/nwstex...,https://mesonet.agron.iastate.edu/p.php?pid=20...,https://mesonet.agron.iastate.edu/vtec/f/2021-...

In [4]:
extractor.save(events, "events.csv")

15:18:05  INFO     Saved 16,086 rows to ../data/extracted/events.csv

PosixPath('../data/extracted/events.csv')

## Storm Reports

One row per Local Storm Report (LSR). The `warned` boolean indicates whether a warning was in effect at the time of the report. Warned reports link back to the events table via the `events` foreign key column; unwarned reports (`warned=False`) have null `events` and `leadtime` values and represent misses in POD calculations.

In [5]:
stormreports = extractor.extract_stormreports()
print(f"{len(stormreports):,} rows × {len(stormreports.columns)} columns")
stormreports.head()

15:18:05  INFO     Extracting stormreports from ABQ_2020.json ...
15:18:05  INFO     Extracting stormreports from ABQ_2021.json ...
15:18:05  INFO     Extracting stormreports from ABQ_2022.json ...
15:18:05  INFO     Extracting stormreports from ABQ_2023.json ...
15:18:05  INFO     Extracting stormreports from ABQ_2024.json ...
15:18:05  INFO     Extracting stormreports from ABQ_2025.json ...
15:18:05  INFO     Extracting stormreports from ABR_2020.json ...
15:18:05  INFO     Extracting stormreports from ABR_2021.json ...
15:18:05  INFO     Extracting stormreports from ABR_2022.json ...
15:18:05  INFO     Extracting stormreports from ABR_2023.json ...
15:18:05  INFO     Extracting stormreports from ABR_2024.json ...
15:18:05  INFO     Extracting stormreports from ABR_2025.json ...
15:18:05  INFO     Extracting stormreports from AFC_2020.json ...
15:18:05  WARNING  AFC_2020.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from AFC_2021.json ...
15:18:05  WARNING  AFC_2021.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from AFC_2022.json ...
15:18:05  WARNING  AFC_2022.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from AFC_2023.json ...
15:18:05  WARNING  AFC_2023.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from AFC_2024.json ...
15:18:05  INFO     Extracting stormreports from AFC_2025.json ...
15:18:05  WARNING  AFC_2025.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from AFG_2020.json ...
15:18:05  WARNING  AFG_2020.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from AFG_2021.json ...
15:18:05  WARNING  AFG_2021.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from AFG_2022.json ...
15:18:05  WARNING  AFG_2022.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from AFG_2023.json ...
15:18:05  WARNING  AFG_2023.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from AFG_2024.json ...
15:18:05  WARNING  AFG_2024.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from AFG_2025.json ...
15:18:05  WARNING  AFG_2025.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from AJK_2020.json ...
15:18:05  WARNING  AJK_2020.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from AJK_2021.json ...
15:18:05  WARNING  AJK_2021.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from AJK_2022.json ...
15:18:05  WARNING  AJK_2022.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from AJK_2023.json ...
15:18:05  WARNING  AJK_2023.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from AJK_2024.json ...
15:18:05  WARNING  AJK_2024.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from AJK_2025.json ...
15:18:05  WARNING  AJK_2025.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from AKQ_2020.json ...
15:18:05  INFO     Extracting stormreports from AKQ_2021.json ...
15:18:05  INFO     Extracting stormreports from AKQ_2022.json ...
15:18:05  INFO     Extracting stormreports from AKQ_2023.json ...
15:18:05  INFO     Extracting stormreports from AKQ_2024.json ...
15:18:05  INFO     Extracting stormreports from AKQ_2025.json ...
15:18:05  INFO     Extracting stormreports from ALY_2020.json ...
15:18:05  INFO     Extracting stormreports from ALY_2021.json ...
15:18:05  INFO     Extracting stormreports from ALY_2022.json ...
15:18:05  INFO     Extracting stormreports from ALY_2023.json ...
15:18:05  INFO     Extracting stormreports from ALY_2024.json ...
15:18:05  INFO     Extracting stormreports from ALY_2025.json ...
15:18:05  WARNING  ALY_2025.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from AMA_2020.json ...
15:18:05  INFO     Extracting stormreports from AMA_2021.json ...
15:18:05  INFO     Extracting stormreports from AMA_2022.json ...
15:18:05  INFO     Extracting stormreports from AMA_2023.json ...
15:18:05  INFO     Extracting stormreports from AMA_2024.json ...
15:18:05  INFO     Extracting stormreports from AMA_2025.json ...
15:18:05  INFO     Extracting stormreports from APX_2020.json ...
15:18:05  WARNING  APX_2020.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from APX_2021.json ...
15:18:05  WARNING  APX_2021.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from APX_2022.json ...
15:18:05  INFO     Extracting stormreports from APX_2023.json ...
15:18:05  WARNING  APX_2023.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from APX_2024.json ...
15:18:05  INFO     Extracting stormreports from APX_2025.json ...
15:18:05  INFO     Extracting stormreports from ARX_2020.json ...
15:18:05  INFO     Extracting stormreports from ARX_2021.json ...
15:18:05  INFO     Extracting stormreports from ARX_2022.json ...
15:18:05  INFO     Extracting stormreports from ARX_2023.json ...
15:18:05  INFO     Extracting stormreports from ARX_2024.json ...
15:18:05  INFO     Extracting stormreports from ARX_2025.json ...
15:18:05  INFO     Extracting stormreports from BGM_2020.json ...
15:18:05  WARNING  BGM_2020.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from BGM_2021.json ...
15:18:05  INFO     Extracting stormreports from BGM_2022.json ...
15:18:05  INFO     Extracting stormreports from BGM_2023.json ...
15:18:05  INFO     Extracting stormreports from BGM_2024.json ...
15:18:05  INFO     Extracting stormreports from BGM_2025.json ...
15:18:05  INFO     Extracting stormreports from BIS_2020.json ...
15:18:05  INFO     Extracting stormreports from BIS_2021.json ...
15:18:05  INFO     Extracting stormreports from BIS_2022.json ...
15:18:05  INFO     Extracting stormreports from BIS_2023.json ...
15:18:05  INFO     Extracting stormreports from BIS_2024.json ...
15:18:05  INFO     Extracting stormreports from BIS_2025.json ...
15:18:05  INFO     Extracting stormreports from BMX_2020.json ...
15:18:05  INFO     Extracting stormreports from BMX_2021.json ...
15:18:05  INFO     Extracting stormreports from BMX_2022.json ...
15:18:05  INFO     Extracting stormreports from BMX_2023.json ...
15:18:05  INFO     Extracting stormreports from BMX_2024.json ...
15:18:05  INFO     Extracting stormreports from BMX_2025.json ...
15:18:05  INFO     Extracting stormreports from BOI_2020.json ...
15:18:05  WARNING  BOI_2020.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from BOI_2021.json ...
15:18:05  WARNING  BOI_2021.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from BOI_2022.json ...
15:18:05  INFO     Extracting stormreports from BOI_2023.json ...
15:18:05  INFO     Extracting stormreports from BOI_2024.json ...
15:18:05  WARNING  BOI_2024.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from BOI_2025.json ...
15:18:05  WARNING  BOI_2025.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from BOU_2020.json ...
15:18:05  INFO     Extracting stormreports from BOU_2021.json ...
15:18:05  INFO     Extracting stormreports from BOU_2022.json ...
15:18:05  INFO     Extracting stormreports from BOU_2023.json ...
15:18:05  INFO     Extracting stormreports from BOU_2024.json ...
15:18:05  INFO     Extracting stormreports from BOU_2025.json ...
15:18:05  INFO     Extracting stormreports from BOX_2020.json ...
15:18:05  INFO     Extracting stormreports from BOX_2021.json ...
15:18:05  INFO     Extracting stormreports from BOX_2022.json ...
15:18:05  WARNING  BOX_2022.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from BOX_2023.json ...
15:18:05  INFO     Extracting stormreports from BOX_2024.json ...
15:18:05  INFO     Extracting stormreports from BOX_2025.json ...
15:18:05  INFO     Extracting stormreports from BRO_2020.json ...
15:18:05  INFO     Extracting stormreports from BRO_2021.json ...
15:18:05  WARNING  BRO_2021.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from BRO_2022.json ...
15:18:05  WARNING  BRO_2022.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from BRO_2023.json ...
15:18:05  INFO     Extracting stormreports from BRO_2024.json ...
15:18:05  WARNING  BRO_2024.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from BRO_2025.json ...
15:18:05  INFO     Extracting stormreports from BTV_2020.json ...
15:18:05  WARNING  BTV_2020.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from BTV_2021.json ...
15:18:05  INFO     Extracting stormreports from BTV_2022.json ...
15:18:05  INFO     Extracting stormreports from BTV_2023.json ...
15:18:05  INFO     Extracting stormreports from BTV_2024.json ...
15:18:05  INFO     Extracting stormreports from BTV_2025.json ...
15:18:05  INFO     Extracting stormreports from BUF_2020.json ...
15:18:05  INFO     Extracting stormreports from BUF_2021.json ...
15:18:05  INFO     Extracting stormreports from BUF_2022.json ...
15:18:05  INFO     Extracting stormreports from BUF_2023.json ...
15:18:05  INFO     Extracting stormreports from BUF_2024.json ...
15:18:05  INFO     Extracting stormreports from BUF_2025.json ...
15:18:05  INFO     Extracting stormreports from BYZ_2020.json ...
15:18:05  WARNING  BYZ_2020.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from BYZ_2021.json ...
15:18:05  WARNING  BYZ_2021.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from BYZ_2022.json ...
15:18:05  WARNING  BYZ_2022.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from BYZ_2023.json ...
15:18:05  WARNING  BYZ_2023.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from BYZ_2024.json ...
15:18:05  WARNING  BYZ_2024.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from BYZ_2025.json ...
15:18:05  INFO     Extracting stormreports from CAE_2020.json ...
15:18:05  INFO     Extracting stormreports from CAE_2021.json ...
15:18:05  INFO     Extracting stormreports from CAE_2022.json ...
15:18:05  INFO     Extracting stormreports from CAE_2023.json ...
15:18:05  INFO     Extracting stormreports from CAE_2024.json ...
15:18:05  INFO     Extracting stormreports from CAE_2025.json ...
15:18:05  INFO     Extracting stormreports from CAR_2020.json ...
15:18:05  WARNING  CAR_2020.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from CAR_2021.json ...
15:18:05  WARNING  CAR_2021.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from CAR_2022.json ...
15:18:05  INFO     Extracting stormreports from CAR_2023.json ...
15:18:05  WARNING  CAR_2023.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from CAR_2024.json ...
15:18:05  WARNING  CAR_2024.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from CAR_2025.json ...
15:18:05  WARNING  CAR_2025.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from CHS_2020.json ...
15:18:05  INFO     Extracting stormreports from CHS_2021.json ...
15:18:05  INFO     Extracting stormreports from CHS_2022.json ...
15:18:05  INFO     Extracting stormreports from CHS_2023.json ...
15:18:05  INFO     Extracting stormreports from CHS_2024.json ...
15:18:05  INFO     Extracting stormreports from CHS_2025.json ...
15:18:05  INFO     Extracting stormreports from CLE_2020.json ...
15:18:05  INFO     Extracting stormreports from CLE_2021.json ...
15:18:05  INFO     Extracting stormreports from CLE_2022.json ...
15:18:05  INFO     Extracting stormreports from CLE_2023.json ...
15:18:05  INFO     Extracting stormreports from CLE_2024.json ...
15:18:05  INFO     Extracting stormreports from CLE_2025.json ...
15:18:05  INFO     Extracting stormreports from CRP_2020.json ...
15:18:05  INFO     Extracting stormreports from CRP_2021.json ...
15:18:05  INFO     Extracting stormreports from CRP_2022.json ...
15:18:05  INFO     Extracting stormreports from CRP_2023.json ...
15:18:05  INFO     Extracting stormreports from CRP_2024.json ...
15:18:05  INFO     Extracting stormreports from CRP_2025.json ...
15:18:05  INFO     Extracting stormreports from CTP_2020.json ...
15:18:05  WARNING  CTP_2020.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from CTP_2021.json ...
15:18:05  INFO     Extracting stormreports from CTP_2022.json ...
15:18:05  INFO     Extracting stormreports from CTP_2023.json ...
15:18:05  INFO     Extracting stormreports from CTP_2024.json ...
15:18:05  INFO     Extracting stormreports from CTP_2025.json ...
15:18:05  INFO     Extracting stormreports from CYS_2020.json ...
15:18:05  INFO     Extracting stormreports from CYS_2021.json ...
15:18:05  INFO     Extracting stormreports from CYS_2022.json ...
15:18:05  INFO     Extracting stormreports from CYS_2023.json ...
15:18:05  INFO     Extracting stormreports from CYS_2024.json ...
15:18:05  INFO     Extracting stormreports from CYS_2025.json ...
15:18:05  INFO     Extracting stormreports from DDC_2020.json ...
15:18:05  INFO     Extracting stormreports from DDC_2021.json ...
15:18:05  INFO     Extracting stormreports from DDC_2022.json ...
15:18:05  INFO     Extracting stormreports from DDC_2023.json ...
15:18:05  INFO     Extracting stormreports from DDC_2024.json ...
15:18:05  INFO     Extracting stormreports from DDC_2025.json ...
15:18:05  INFO     Extracting stormreports from DLH_2020.json ...
15:18:05  INFO     Extracting stormreports from DLH_2021.json ...
15:18:05  INFO     Extracting stormreports from DLH_2022.json ...
15:18:05  INFO     Extracting stormreports from DLH_2023.json ...
15:18:05  WARNING  DLH_2023.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from DLH_2024.json ...
15:18:05  INFO     Extracting stormreports from DLH_2025.json ...
15:18:05  INFO     Extracting stormreports from DMX_2020.json ...
15:18:05  INFO     Extracting stormreports from DMX_2021.json ...
15:18:05  INFO     Extracting stormreports from DMX_2022.json ...
15:18:05  INFO     Extracting stormreports from DMX_2023.json ...
15:18:05  INFO     Extracting stormreports from DMX_2024.json ...
15:18:05  INFO     Extracting stormreports from DMX_2025.json ...
15:18:05  INFO     Extracting stormreports from DTX_2020.json ...
15:18:05  WARNING  DTX_2020.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from DTX_2021.json ...
15:18:05  INFO     Extracting stormreports from DTX_2022.json ...
15:18:05  INFO     Extracting stormreports from DTX_2023.json ...
15:18:05  INFO     Extracting stormreports from DTX_2024.json ...
15:18:05  INFO     Extracting stormreports from DTX_2025.json ...
15:18:05  INFO     Extracting stormreports from DVN_2020.json ...
15:18:05  INFO     Extracting stormreports from DVN_2021.json ...
15:18:05  INFO     Extracting stormreports from DVN_2022.json ...
15:18:05  INFO     Extracting stormreports from DVN_2023.json ...
15:18:05  INFO     Extracting stormreports from DVN_2024.json ...
15:18:05  INFO     Extracting stormreports from DVN_2025.json ...
15:18:05  INFO     Extracting stormreports from EAX_2020.json ...
15:18:05  INFO     Extracting stormreports from EAX_2021.json ...
15:18:05  INFO     Extracting stormreports from EAX_2022.json ...
15:18:05  INFO     Extracting stormreports from EAX_2023.json ...
15:18:05  INFO     Extracting stormreports from EAX_2024.json ...
15:18:05  INFO     Extracting stormreports from EAX_2025.json ...
15:18:05  INFO     Extracting stormreports from EKA_2020.json ...
15:18:05  WARNING  EKA_2020.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from EKA_2021.json ...
15:18:05  WARNING  EKA_2021.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from EKA_2022.json ...
15:18:05  WARNING  EKA_2022.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from EKA_2023.json ...
15:18:05  INFO     Extracting stormreports from EKA_2024.json ...
15:18:05  WARNING  EKA_2024.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from EKA_2025.json ...
15:18:05  WARNING  EKA_2025.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from EPZ_2020.json ...
15:18:05  INFO     Extracting stormreports from EPZ_2021.json ...
15:18:05  WARNING  EPZ_2021.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from EPZ_2022.json ...
15:18:05  WARNING  EPZ_2022.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from EPZ_2023.json ...
15:18:05  WARNING  EPZ_2023.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from EPZ_2024.json ...
15:18:05  WARNING  EPZ_2024.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from EPZ_2025.json ...
15:18:05  WARNING  EPZ_2025.json: no stormreports found, skipping
15:18:05  INFO     Extracting stormreports from EWX_2020.json ...
15:18:05  INFO     Extracting stormreports from EWX_2021.json ...
15:18:05  INFO     Extracting stormreports from EWX_2022.json ...
15:18:05  INFO     Extracting stormreports from EWX_2023.json ...
15:18:05  INFO     Extracting stormreports from EWX_2024.json ...
15:18:05  INFO     Extracting stormreports from EWX_2025.json ...
15:18:05  INFO     Extracting stormreports from FFC_2020.json ...
15:18:05  INFO     Extracting stormreports from FFC_2021.json ...
15:18:05  INFO     Extracting stormreports from FFC_2022.json ...
15:18:05  INFO     Extracting stormreports from FFC_2023.json ...
15:18:05  INFO     Extracting stormreports from FFC_2024.json ...
15:18:05  INFO     Extracting stormreports from FFC_2025.json ...
15:18:05  INFO     Extracting stormreports from FGF_2020.json ...
15:18:05  INFO     Extracting stormreports from FGF_2021.json ...
15:18:05  INFO     Extracting stormreports from FGF_2022.json ...
15:18:05  INFO     Extracting stormreports from FGF_2023.json ...
15:18:05  INFO     Extracting stormreports from FGF_2024.json ...
15:18:05  INFO     Extracting stormreports from FGF_2025.json ...
15:18:05  INFO     Extracting stormreports from FGZ_2020.json ...
15:18:05  INFO     Extracting stormreports from FGZ_2021.json ...
15:18:05  INFO     Extracting stormreports from FGZ_2022.json ...
15:18:05  INFO     Extracting stormreports from FGZ_2023.json ...
15:18:05  INFO     Extracting stormreports from FGZ_2024.json ...
15:18:05  INFO     Extracting stormreports from FGZ_2025.json ...
15:18:05  INFO     Extracting stormreports from FSD_2020.json ...
15:18:05  INFO     Extracting stormreports from FSD_2021.json ...
15:18:05  INFO     Extracting stormreports from FSD_2022.json ...
15:18:05  INFO     Extracting stormreports from FSD_2023.json ...
15:18:05  INFO     Extracting stormreports from FSD_2024.json ...
15:18:05  INFO     Extracting stormreports from FSD_2025.json ...
15:18:05  INFO     Extracting stormreports from FWD_2020.json ...
15:18:05  INFO     Extracting stormreports from FWD_2021.json ...
15:18:05  INFO     Extracting stormreports from FWD_2022.json ...
15:18:05  INFO     Extracting stormreports from FWD_2023.json ...
15:18:05  INFO     Extracting stormreports from FWD_2024.json ...
15:18:05  INFO     Extracting stormreports from FWD_2025.json ...
15:18:05  INFO     Extracting stormreports from GGW_2020.json ...
15:18:05  INFO     Extracting stormreports from GGW_2021.json ...
15:18:05  WARNING  GGW_2021.json: no stormreports found, skipping

10,708 rows × 19 columns

,wfo,year,valid,type,magnitude,city,county,state,source,remark,typetext,lon0,lat0,events,tdq,warned,leadtime,lsrtype,link
0,ABQ,2020,2020-03-17T23:24:00Z,T,None,PLEASANT HILL,CURRY,NM,SOCIAL MEDIA,NaN,TORNADO,-103.07,34.52,,False,False,None,TO,https://mesonet.agron.iastate.edu/lsr/#ABQ/202...
1,ABQ,2020,2020-03-21T20:30:00Z,T,None,6 S KIRTLAND,SAN JUAN,NM,PUBLIC,LANDSPOUT TORNADO OVER NAVAJO AGRICULTURAL PRO...,TORNADO,-108.34,36.65,,False,False,None,TO,https://mesonet.agron.iastate.edu/lsr/#ABQ/202...
2,ABQ,2020,2020-07-04T22:30:00Z,T,None,13 W GRENVILLE,UNION,NM,STORM CHASER,NaN,TORNADO,-103.85,36.59,,False,False,None,TO,https://mesonet.agron.iastate.edu/lsr/#ABQ/202...
3,ABQ,2020,2020-07-15T23:03:00Z,T,None,3 E VEGUITA,SOCORRO,NM,NWS EMPLOYEE,LANDSPOUT OCCURRED FOR ABOUT 15 MINUTES.,TORNADO,-106.71,34.52,,False,False,None,TO,https://mesonet.agron.iastate.edu/lsr/#ABQ/202...
4,ABQ,2021,2021-01-25T14:15:00Z,T,None,4 NNE CHACON,MORA,NM,TRAINED SPOTTER,NaN,TORNADO,-105.35,36.20,,False,False,NaN,TO,https://mesonet.agron.iastate.edu/lsr/#ABQ/202...

In [6]:
extractor.save(stormreports, "stormreports.csv")

15:18:06  INFO     Saved 10,708 rows to ../data/extracted/stormreports.csv

PosixPath('../data/extracted/stormreports.csv')